### ISSUE TITLE
关于flask-admin的一个疑问

### ISSUE THREAD

**Issue by jiamengwei** [huang-zp/MagicPress#1]
https://www.cnblogs.com/magicroc/p/6103773.html?utm_source=itdadao&utm_medium=referral
我是在上面这个链接看到的你，我有一个小小的疑问想向你请教，
我在使用flask-admin生成的后台的时候遇到了一个问题，我有一个文章分类表Category和一个文章表Article，在我添加一个文章后，再去添加分类会出现错误：ValueError: too many values to unpack (expected 2)
而且删除一个文章分类的时候（这个分类下有文章），可以直接删除。。。这样的话外键不是没意义了么

```
class Article(db.Model):
    __tablename__ = 'article'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(20), nullable=False)
    writer = db.Column(db.String(10), nullable=False)
    content = db.Column(db.Text, nullable=False)
    add_time = db.Column(db.DateTime,  default=datetime.now)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    comment = db.relationship('Comment', backref='article', lazy='dynamic')

    def __repr__(self):
        return '<title %r>' % self.title

class Category(db.Model):

    __tablename__ = 'category'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(10), nullable=False,unique=True)
    description = db.Column(db.String(120), nullable=False)
    add_time = db.Column(db.DateTime, default=datetime.now)
    articel = db.relationship('Article', backref='category', lazy='dynamic')

    def __repr__(self):
        return '<name %r>' % self.name
```

**Comment by huang-zp** [comment]
当你添加分类的时候是去Category表中新建一个实例再去文章中选择这个实例吗？
ValueError: too many values to unpack (expected 2)这种错误一般是把一个列表、元组这样的数据结构的值拿出来赋值给接收方，接收方变量个数不够造成到错误
例如：

Python 3.6.4 (default, Feb  5 2018, 14:21:54) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>>> a, b = [1, 2, 3]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack (expected 2)
\>>> a, b = (1, 2, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack (expected 2)
\>>> a, b, c = (1, 2, 3)
\>>> a
1
\>>> b
2
\>>> c
3
